//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v2.0.5.6
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PayHub.DB.Data
{
   public partial class WithdrawAccount
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected WithdrawAccount()
      {
         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static WithdrawAccount CreateWithdrawAccountUnsafe()
      {
         return new WithdrawAccount();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="userid"></param>
      /// <param name="currencyid"></param>
      /// <param name="account"></param>
      /// <param name="name"></param>
      public WithdrawAccount(string userid, string currencyid, string account, string name)
      {
         if (string.IsNullOrEmpty(userid)) throw new ArgumentNullException(nameof(userid));
         this.UserId = userid;

         if (string.IsNullOrEmpty(currencyid)) throw new ArgumentNullException(nameof(currencyid));
         this.CurrencyId = currencyid;

         if (string.IsNullOrEmpty(account)) throw new ArgumentNullException(nameof(account));
         this.Account = account;

         if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
         this.Name = name;


         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="userid"></param>
      /// <param name="currencyid"></param>
      /// <param name="account"></param>
      /// <param name="name"></param>
      public static WithdrawAccount Create(string userid, string currencyid, string account, string name)
      {
         return new WithdrawAccount(userid, currencyid, account, name);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required, Min length = 32, Max length = 32
      /// </summary>
      [Key]
      [Required]
      [MinLength(32)]
      [MaxLength(32)]
      [StringLength(32)]
      public string Id { get; protected set; }

      /// <summary>
      /// Indexed, Required, Min length = 32, Max length = 32
      /// </summary>
      [Required]
      [MinLength(32)]
      [MaxLength(32)]
      [StringLength(32)]
      public string UserId { get; set; }

      /// <summary>
      /// Indexed, Required, Min length = 32, Max length = 32
      /// </summary>
      [Required]
      [MinLength(32)]
      [MaxLength(32)]
      [StringLength(32)]
      public string CurrencyId { get; set; }

      /// <summary>
      /// Required, Min length = 1, Max length = 256
      /// </summary>
      [Required]
      [MinLength(1)]
      [MaxLength(256)]
      [StringLength(256)]
      public string Account { get; set; }

      /// <summary>
      /// Indexed, Required, Min length = 1, Max length = 256
      /// </summary>
      [Required]
      [MinLength(1)]
      [MaxLength(256)]
      [StringLength(256)]
      public string Name { get; set; }

   }
}

